### ISSUE TITLE
Ask: Da lao for github emoji

### ISSUE THREAD

**Issue by Jacky-Summer** [DawnLck/FrontendDiscipline#1]
我想问下大佬你用的git commit emoji 表情用的哪种方式，我用的这个[通过 Emoji 表情标识 Git 每次提交的信息](https://www.cnblogs.com/myzony/p/9578790.html)，但是鼠标移动上去或者git log就会看到 `:memo:`类似这样的英文提示，你的我看没有，也没有安装库，想问是怎么弄的，谢谢！！！:pray:

**Comment by DawnLck** [comment]
我习惯用VsCode提交，VsCode的插件市场里搜一下Git emoji commit，安装就能使用了。其实npm仓库里应该也有类似的插件，方便你在控制台提交的时候选择对应的提交类型和emoji，你也可以搜索一下。

**Comment by Jacky-Summer** [comment]
> 我习惯用VsCode提交，VsCode的插件市场里搜一下Git emoji commit，安装就能使用了。其实npm仓库里应该也有类似的插件，方便你在控制台提交的时候选择对应的提交类型和emoji，你也可以搜索一下。

好，谢谢
